#!/bin/sh
# build-release.sh — cross-compile the yamlet CLI for every shipped target and
# package each as a tarball with a checksums file, ready to attach to a GitHub
# Release. Run from the `tooling/` directory:
#
#   ./scripts/build-release.sh 0.1.0
#
# Deno cross-compiles from any single host (no native toolchain per target), so
# CI runs this once on one runner. The viewer assets are embedded with the same
# --include flags as the `compile` task, so each binary is self-contained.
#
# The version is stamped into src/version.ts for the duration of the build and
# restored afterwards, so a local run leaves the working tree clean.
set -eu

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
    printf 'usage: build-release.sh <version>   (e.g. 0.1.0, no leading v)\n' >&2
    exit 2
fi

# Resolve paths relative to this script so it works from any CWD.
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TOOLING_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
REPO_DIR=$(CDPATH= cd -- "$TOOLING_DIR/.." && pwd)
cd "$TOOLING_DIR"

DIST="$TOOLING_DIR/dist"
VERSION_FILE="$TOOLING_DIR/src/version.ts"

TARGETS="x86_64-apple-darwin aarch64-apple-darwin x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu"

# Pick a checksum tool up front (Linux: sha256sum, macOS: shasum -a 256).
if command -v sha256sum >/dev/null 2>&1; then
    sha256() { sha256sum "$@"; }
elif command -v shasum >/dev/null 2>&1; then
    sha256() { shasum -a 256 "$@"; }
else
    printf 'build-release: no sha256sum or shasum found\n' >&2
    exit 1
fi

# Stamp the real version in, and guarantee we put the placeholder back even on
# failure so a local invocation never leaves version.ts dirty. Back up by copying
# bytes (not $(cat …), which would drop the trailing newline and dirty the tree).
VERSION_BACKUP=$(mktemp)
cp "$VERSION_FILE" "$VERSION_BACKUP"
restore_version() { cp "$VERSION_BACKUP" "$VERSION_FILE"; rm -f "$VERSION_BACKUP"; }
trap restore_version EXIT INT TERM
cat >"$VERSION_FILE" <<EOF
// Generated by scripts/build-release.sh for the v$VERSION release build.
// In the source tree this is the placeholder \`0.0.0-dev\`; keep it to just the
// constant so the build can overwrite this file wholesale.
export const VERSION = "$VERSION";
EOF

rm -rf "$DIST"
mkdir -p "$DIST"

for target in $TARGETS; do
    printf '==> compiling %s\n' "$target"
    deno compile \
        --allow-read --allow-write \
        --target "$target" \
        --include src/viewer/template.html \
        --include src/viewer/viewer.css \
        --include src/viewer/viewer.js \
        --include src/viewer/vendor/elk.bundled.js \
        --output "$DIST/yamlet" \
        main.ts

    stage="$DIST/stage-$target"
    mkdir -p "$stage"
    mv "$DIST/yamlet" "$stage/yamlet"
    cp "$REPO_DIR/LICENSE" "$stage/LICENSE"

    archive="yamlet-$VERSION-$target.tar.gz"
    tar -czf "$DIST/$archive" -C "$stage" yamlet LICENSE
    rm -rf "$stage"
    printf '    packaged %s\n' "$archive"
done

# One checksums file over the archives, filenames only (so `sha256sum -c` works
# from within dist/ and the tap renderer can grep by archive name).
( cd "$DIST" && sha256 yamlet-"$VERSION"-*.tar.gz >SHA256SUMS )

printf '\nBuilt artifacts in %s:\n' "$DIST"
ls -1 "$DIST"
