// `yamlet docs` — render specs and decision records as Markdown for people.
//
// The YAML is the source of truth and stays the only thing anyone edits. This
// command projects it into a tree of Markdown pages meant to be committed and
// read where the code lives (GitHub, GitLab, an IDE preview) by teammates and
// stakeholders who never run the CLI:
//
//   TARGET/index.md                  every system and its scopes, every decision, a map of
//                                    which composite holds which scope
//   TARGET/<system>/<scope>.md       one per spec: contract, members and wiring (composites),
//                                    requirements with each criterion as an EARS sentence,
//                                    the decisions that decide them, who uses the scope
//   TARGET/decisions/<…>/<adr>.md    one per decision record, every status — a rejected or
//                                    superseded record is history, rendered and marked as such
//
// Tech specs are deliberately not rendered: they are disposable plans, and a
// committed rendering would outlive the plan it shows. Progress is `yamlet trace`.
//
// Because the output is committed, it can go stale. `--check` regenerates in
// memory and compares with TARGET without writing: exit 1 names every page that
// is missing, changed or no longer produced — the CI gate that keeps the pages
// honest. Every page opens with a "generated, do not edit" comment and links its
// source file, so a reader always knows where the truth lives.
//
// TARGET is a yamlet-owned directory, as for `yamlet tests`: every run wipes it
// and rebuilds, so a renamed or deleted spec never leaves an orphan page. Unlike a
// feature tree, a docs directory is a plausible place for hand-written files, so
// the wipe is guarded: a non-empty TARGET whose index.md was not written by this
// command is refused, and so is a TARGET that contains SRC.
//
// Parse, never validate: a file that does not parse is skipped and listed; a link
// that resolves to nothing renders as plain text. `yamlet verify` stays the judge.
//
// Exit codes: 0 ok (or up to date) · 1 --check found drift · 2 usage/path/collision/write error.

import type { CmdResult, Command, FlatRecord } from "./types.ts";
import { flatten } from "./flatten.ts";
import { joinNorm } from "./cmd.ts";
import { indicesUnder, listUnder } from "./records.ts";
import { listFiles, listSpecs } from "./systems.ts";
import { type Adr, loadAdr, SPEC_REF_RE } from "./adr.ts";

const die = (msg: string): CmdResult => ({ exitCode: 2, stdout: "", stderr: `error: ${msg}\n` });

/** First line of every page; also how a TARGET proves it is ours before a wipe. */
const MARKER = "<!-- Generated by `yamlet docs`";
const header = (source: string): string =>
  `${MARKER} from ${source}. Do not edit: changes are overwritten on the next run. -->\n\n`;

// ── the structured view of a spec ─────────────────────────────────────────

interface Criterion {
  id: string;
  pattern: string;
  where: string;
  whiles: string[];
  when: string;
  ifCond: string;
  shalls: string[];
  exampleKeys: string[];
  exampleRows: Record<string, string>[];
  reads: string[];
  writes: string[];
  adrs: string[];
}
interface Requirement {
  id: string;
  description: string;
  adrs: string[];
  criteria: Criterion[];
}
interface Member {
  alias: string;
  path: string; // as written, relative to the composite
}
interface Wire {
  group: string; // member alias, or "output"
  sink: string;
  source: string; // `input.X` or `alias.socket`
}
interface SpecDoc {
  key: string; // normalized path of the source file
  system: string;
  topic: string;
  summary: string;
  description: string;
  front: string;
  blastRadius: string;
  name: string;
  intent: string;
  inputs: string[];
  outputs: string[];
  members: Member[];
  wires: Wire[];
  requirements: Requirement[];
}

function examplesUnder(
  records: readonly FlatRecord[],
  prefix: string,
): { keys: string[]; rows: Record<string, string>[] } {
  const esc = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`^${esc}\\.examples\\[(\\d+)\\]\\.(.+)$`);
  const byRow = new Map<number, Record<string, string>>();
  const keys = new Set<string>();
  for (const r of records) {
    const m = r.path.match(re);
    if (!m) continue;
    keys.add(m[2]!);
    const row = byRow.get(Number(m[1])) ?? {};
    row[m[2]!] = r.value;
    byRow.set(Number(m[1]), row);
  }
  return {
    keys: [...keys],
    rows: [...byRow.keys()].sort((a, b) => a - b).map((i) => byRow.get(i)!),
  };
}

function parseSpec(key: string, records: readonly FlatRecord[]): SpecDoc {
  const get = (p: string): string => records.find((r) => r.path === p)?.value ?? "";
  const requirements: Requirement[] = indicesUnder(records, "requirements").map((i) => {
    const rq = `requirements[${i}]`;
    return {
      id: get(`${rq}.id`),
      description: get(`${rq}.description`),
      adrs: listUnder(records, `${rq}.adrs`),
      criteria: indicesUnder(records, `${rq}.acceptance-criteria`).map((j) => {
        const ac = `${rq}.acceptance-criteria[${j}]`;
        const { keys, rows } = examplesUnder(records, ac);
        return {
          id: get(`${ac}.id`),
          pattern: get(`${ac}.pattern`),
          where: get(`${ac}.where`),
          whiles: listUnder(records, `${ac}.while`),
          when: get(`${ac}.when`),
          ifCond: get(`${ac}.if`),
          shalls: listUnder(records, `${ac}.shall`),
          exampleKeys: keys,
          exampleRows: rows,
          reads: listUnder(records, `${ac}.reads`),
          writes: listUnder(records, `${ac}.writes`),
          adrs: listUnder(records, `${ac}.adrs`),
        };
      }),
    };
  });
  const members: Member[] = [];
  const wires: Wire[] = [];
  for (const r of records) {
    const m = r.path.match(/^components\[\d+\]\.([^.]+)$/);
    if (m) members.push({ alias: m[1]!, path: r.value });
    const w = r.path.match(/^connections\.([^.]+)\.([^.]+)$/);
    if (w) wires.push({ group: w[1]!, sink: w[2]!, source: r.value });
  }
  return {
    key,
    system: get("system"),
    topic: get("topic"),
    summary: get("summary"),
    description: get("description"),
    front: get("front"),
    blastRadius: get("blast_radius"),
    name: get("exposes.name"),
    intent: get("exposes.intent"),
    inputs: listUnder(records, "exposes.inputs"),
    outputs: listUnder(records, "exposes.outputs"),
    members,
    wires,
    requirements,
  };
}

// ── paths and links ───────────────────────────────────────────────────────

const dirOf = (p: string): string => (p.includes("/") ? p.slice(0, p.lastIndexOf("/")) : "");
const baseOf = (p: string): string => p.slice(p.lastIndexOf("/") + 1);

/** `to` relative to the directory `fromDir` (both normalized, same root). */
function relative(fromDir: string, to: string): string {
  const a = fromDir.split("/").filter((s) => s !== "");
  const b = to.split("/").filter((s) => s !== "");
  let i = 0;
  while (i < a.length && i < b.length - 1 && a[i] === b[i]) i++;
  return [...a.slice(i).map(() => ".."), ...b.slice(i)].join("/");
}

/** A link target safe inside `(…)`: spaces and parentheses percent-encoded. */
const href = (p: string): string =>
  p.replace(/ /g, "%20").replace(/\(/g, "%28").replace(/\)/g, "%29");

/** An absolute, normalized path: real where it exists, so a symlinked SRC and TARGET agree. */
function absPath(p: string): string {
  try {
    return Deno.realPathSync(p);
  } catch {
    return joinNorm(Deno.cwd(), p);
  }
}

// ── Markdown text ─────────────────────────────────────────────────────────

/**
 * Escape prose for Markdown. `_` is escaped only at a word edge: GFM never
 * reads an intra-word underscore (`archive_address`) as emphasis, and escaping it
 * would litter the source people also read in diffs.
 */
function esc(s: string): string {
  return s
    .replace(/[\\`*[\]<>|]/g, "\\$&")
    .replace(/(^|[^A-Za-z0-9])_/g, "$1\\_")
    .replace(/_(?=[^A-Za-z0-9]|$)/g, "\\_");
}

/** Escape prose that starts a block, where a leading `#`, `-`, `+`, `>` or `1.` would be syntax. */
function para(s: string): string {
  return esc(s).replace(/^(#|[-+>]|\d+[.)])/, "\\$1");
}

/** A code span that survives a backtick inside it. */
function code(s: string): string {
  const ticks = s.includes("`") ? "``" : "`";
  const pad = s.startsWith("`") || s.endsWith("`") ? " " : "";
  return `${ticks}${pad}${s}${pad}${ticks}`;
}

/**
 * Criterion prose with its `{…}` tokens made visible: a contract reference
 * (`{input.file}`, `{output.error}`) renders as the socket name in code, a
 * member reference (`{archiver.pdf_file}`) as written, an example-backed
 * placeholder as `<key>` — the value varies by row of the examples table.
 */
function prose(text: string, exampleKeys: ReadonlySet<string>): string {
  let out = "";
  let last = 0;
  for (const m of text.matchAll(/\{([^{}]*)\}/g)) {
    out += esc(text.slice(last, m.index));
    const tok = m[1]!;
    const port = tok.match(/^(?:input|output)\.(.+)$/);
    out += exampleKeys.has(tok) ? code(`<${tok}>`) : code(port ? port[1]! : tok);
    last = m.index! + m[0].length;
  }
  return out + esc(text.slice(last));
}

/** A table cell: no newline, no unescaped pipe. */
const cell = (s: string): string => s.replace(/\s*\n\s*/g, " ");

function table(head: string[], rows: string[][]): string {
  const line = (r: string[]) => `| ${r.map(cell).join(" | ")} |`;
  return [line(head), `|${head.map(() => "---").join("|")}|`, ...rows.map(line)].join("\n") + "\n";
}

/** A page's key facts, one bolded label per line. */
const factList = (facts: string[][]): string =>
  facts.map(([k, v]) => `- **${k}:** ${v}\n`).join("") + "\n";

const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1);
const plural = (n: number, w: string): string => `${n} ${w}${n === 1 ? "" : "s"}`;
const anchor = (id: string): string => id.toLowerCase();

const FRONT: Record<string, string> = {
  external: "External — the caller is outside the trust boundary",
  internal: "Internal — the caller is inside the trust boundary",
};

/** The EARS sentence that introduces a criterion's obligations. */
function earsLead(c: Criterion, keys: ReadonlySet<string>): string {
  const parts: string[] = [];
  if (c.where) parts.push(`where ${prose(c.where, keys)}`);
  if (c.whiles.length > 0) parts.push(`while ${c.whiles.map((w) => prose(w, keys)).join(" and ")}`);
  if (c.when) parts.push(`when ${prose(c.when, keys)}`);
  else if (c.ifCond) parts.push(`if ${prose(c.ifCond, keys)}`);
  const cond = parts.join(", ");
  const lead = cond === ""
    ? "the system shall:"
    : `${cond}, ${c.ifCond && !c.when ? "then " : ""}the system shall:`;
  return cap(lead);
}

// ── the site: what exists and where each page goes ───────────────────────

interface AdrPage {
  key: string; // normalized path of the source file
  page: string; // path inside TARGET
  adr: Adr;
}
interface SpecPage {
  page: string;
  doc: SpecDoc;
}
interface Site {
  srcAbs: string;
  targetAbs: string;
  specs: Map<string, SpecPage>; // by source key
  adrs: Map<string, AdrPage>; // by source key
  /** Composites that hold a spec: member key → [composite key, alias]. */
  usedBy: Map<string, { composite: string; alias: string }[]>;
  /** Spec blocks that link an ADR: ADR key → [spec key, RQ/AC id]. */
  linkedFrom: Map<string, { spec: string; id: string }[]>;
}

function adrInDir(site: Site, dir: string, id: string): AdrPage | undefined {
  for (const a of site.adrs.values()) {
    if (dirOf(a.key) === dir && a.adr.id === id) return a;
  }
  return undefined;
}

/** The source file, linked from a page. */
function sourceLink(site: Site, page: string, key: string): string {
  const from = joinNorm(site.targetAbs, dirOf(page));
  const to = joinNorm(site.srcAbs, key);
  return `[${code(baseOf(key))}](${href(relative(from, to))})`;
}

function adrLabel(a: AdrPage): string {
  return `${a.adr.id || baseOf(a.key)} · ${esc(a.adr.title)}`;
}

/** A link to an ADR page from `page`, with its status; plain text when not rendered. */
function adrRef(site: Site, page: string, key: string, raw: string): string {
  const a = site.adrs.get(key);
  if (!a) return `${code(raw)} (not found under the source directory)`;
  return `[${adrLabel(a)}](${href(relative(dirOf(page), a.page))}) (${
    a.adr.status || "no status"
  })`;
}

function specRef(site: Site, page: string, key: string, id = ""): string {
  const s = site.specs.get(key);
  if (!s) return code(id ? `${baseOf(key)}#${id}` : baseOf(key));
  const label = esc(s.doc.topic || baseOf(key)) + (id ? ` · ${id}` : "");
  return `[${label}](${href(relative(dirOf(page), s.page))}${id ? `#${anchor(id)}` : ""})`;
}

// ── spec page ─────────────────────────────────────────────────────────────

/** A composite's wiring as a Mermaid flowchart: boundary ports, members, and every wire. */
function mermaid(site: Site, doc: SpecDoc): string {
  const id = (s: string) => s.replace(/[^A-Za-z0-9_]/g, "_");
  const q = (s: string) => `"${s.replace(/"/g, "#quot;")}"`;
  const dir = dirOf(doc.key);
  const L = ["```mermaid", "flowchart LR"];
  const ins = new Set<string>();
  const outs = new Set<string>();
  for (const w of doc.wires) {
    const src = w.source.match(/^input\.(.+)$/);
    if (src) ins.add(src[1]!);
    if (w.group === "output") outs.add(w.sink);
  }
  for (const i of doc.inputs.filter((x) => ins.has(x))) L.push(`  in_${id(i)}([${q(i)}])`);
  for (const m of doc.members) {
    const member = site.specs.get(joinNorm(dir, m.path));
    const topic = member?.doc.topic ?? baseOf(m.path);
    L.push(`  m_${id(m.alias)}[${q(`${m.alias}<br/>${topic}`)}]`);
  }
  for (const o of doc.outputs.filter((x) => outs.has(x))) L.push(`  out_${id(o)}([${q(o)}])`);
  for (const w of doc.wires) {
    const to = w.group === "output" ? `out_${id(w.sink)}` : `m_${id(w.group)}`;
    const src = w.source.match(/^input\.(.+)$/);
    const from = src ? `in_${id(src[1]!)}` : `m_${id(w.source.split(".")[0]!)}`;
    const fromSocket = src ? src[1]! : w.source.split(".").slice(1).join(".");
    let label = "";
    if (w.group === "output") label = fromSocket === w.sink ? "" : fromSocket;
    else if (src) label = fromSocket === w.sink ? "" : w.sink;
    else label = fromSocket === w.sink ? w.sink : `${fromSocket} → ${w.sink}`;
    L.push(`  ${from} -->${label ? `|${q(label)}|` : ""} ${to}`);
  }
  L.push("```");
  return L.join("\n") + "\n";
}

function endpoint(e: string): string {
  const m = e.match(/^(input|output)\.(.+)$/);
  return m ? `${code(m[2]!)} (${m[1]} of this scope)` : code(e);
}

function renderSpec(site: Site, sp: SpecPage): string {
  const { doc, page } = sp;
  const dir = dirOf(doc.key);
  let s = header(baseOf(doc.key));
  s += `# ${esc(doc.topic || baseOf(doc.key))}\n\n`;
  if (doc.summary) s += `> ${esc(doc.summary)}\n\n`;

  const facts: string[][] = [
    ["System", `[${esc(doc.system)}](${href(relative(dirOf(page), "index.md"))}#${doc.system})`],
  ];
  if (doc.front) facts.push(["Caller", FRONT[doc.front] ?? esc(doc.front)]);
  if (doc.blastRadius) facts.push(["Blast radius", cap(esc(doc.blastRadius))]);
  facts.push(["Source", sourceLink(site, page, doc.key)]);
  s += factList(facts);
  if (doc.description) s += para(doc.description) + "\n\n";

  if (doc.name) {
    s += "## Contract\n\n";
    s += `${code(doc.name)}${doc.intent ? ` — ${esc(doc.intent)}` : ""}\n\n`;
    const list = (xs: string[]) => (xs.length > 0 ? xs.map(code).join(", ") : "none");
    s += `- **Inputs:** ${list(doc.inputs)}\n- **Outputs:** ${list(doc.outputs)}\n\n`;
  }

  if (doc.members.length > 0) {
    s += "## Members\n\n";
    s += table(
      ["Alias", "Scope", "Summary"],
      doc.members.map((m) => {
        const key = joinNorm(dir, m.path);
        return [
          code(m.alias),
          specRef(site, page, key),
          esc(site.specs.get(key)?.doc.summary ?? ""),
        ];
      }),
    ) + "\n";
  }
  if (doc.wires.length > 0) {
    s += "## Wiring\n\n" + mermaid(site, doc) + "\n";
    s += table(
      ["Into", "From"],
      doc.wires.map((w) => [
        w.group === "output" ? endpoint(`output.${w.sink}`) : code(`${w.group}.${w.sink}`),
        endpoint(w.source),
      ]),
    ) + "\n";
  }

  if (doc.requirements.length > 0) s += "## Requirements\n\n";
  const decided = (adrs: string[]): string =>
    adrs.length === 0
      ? ""
      : `Decided by ${adrs.map((a) => adrRef(site, page, joinNorm(dir, a), a)).join(", ")}\n\n`;
  for (const rq of doc.requirements) {
    s += `<a id="${anchor(rq.id)}"></a>\n\n### ${rq.id} · ${esc(rq.description)}\n\n`;
    s += decided(rq.adrs);
    for (const ac of rq.criteria) {
      const keys = new Set(ac.exampleKeys);
      s += `<a id="${anchor(ac.id)}"></a>\n**${ac.id}** · ${earsLead(ac, keys)}\n\n`;
      for (const sh of ac.shalls) s += `- ${prose(sh, keys)}\n`;
      s += "\n";
      if (ac.exampleRows.length > 0) {
        s += "Examples:\n\n" + table(
          ac.exampleKeys.map((k) => code(`<${k}>`)),
          ac.exampleRows.map((row) => ac.exampleKeys.map((k) => esc(row[k] ?? ""))),
        ) + "\n";
      }
      const state: string[] = [];
      if (ac.reads.length > 0) state.push(`reads ${ac.reads.map(code).join(", ")}`);
      if (ac.writes.length > 0) state.push(`writes ${ac.writes.map(code).join(", ")}`);
      if (state.length > 0) s += `Stored state: ${state.join("; ")}\n\n`;
      s += decided(ac.adrs);
    }
  }

  const users = site.usedBy.get(doc.key) ?? [];
  if (users.length > 0) {
    s += "## Used by\n\n";
    for (const u of users) s += `- ${specRef(site, page, u.composite)} as ${code(u.alias)}\n`;
    s += "\n";
  }
  return s.replace(/\n+$/, "\n");
}

// ── decision page ─────────────────────────────────────────────────────────

const STATUS_NOTE: Record<string, (site: Site, a: AdrPage) => string> = {
  proposed: () => "> [!NOTE]\n> **Proposed.** Under discussion — nothing here is decided yet.\n\n",
  rejected: (_s, a) =>
    `> [!CAUTION]\n> **Rejected.** ${esc(a.adr.rejectedBecause)} Kept as historical context.\n\n`,
  superseded: (site, a) => {
    const next = adrInDir(site, dirOf(a.key), a.adr.supersededBy);
    const by = next
      ? `[${adrLabel(next)}](${href(relative(dirOf(a.page), next.page))})`
      : code(a.adr.supersededBy || "a later record");
    return `> [!WARNING]\n> **Superseded** by ${by}. Kept as historical context.\n\n`;
  },
};

function locator(v: string): string {
  return /^https?:\/\/\S+$/.test(v) ? `<${v}>` : esc(v);
}

function renderAdr(site: Site, ap: AdrPage): string {
  const { adr: a, page, key } = ap;
  const dir = dirOf(key);
  const idLink = (id: string): string => {
    const t = adrInDir(site, dir, id);
    return t ? `[${adrLabel(t)}](${href(relative(dirOf(page), t.page))})` : code(id);
  };
  const chosen = a.options.find((o) => o.id === a.decision);

  let s = header(baseOf(key));
  s += `# ${adrLabel(ap)}\n\n`;
  s += STATUS_NOTE[a.status]?.(site, ap) ?? "";

  const facts: string[][] = [["Status", cap(esc(a.status))], ["Date", esc(a.date)]];
  if (a.kind) facts.push(["Kind", cap(esc(a.kind))]);
  if (chosen) facts.push(["Decision", `${chosen.id} — ${esc(chosen.summary)}`]);
  if (a.arisesFrom.length > 0) {
    facts.push([
      "Arises from",
      a.arisesFrom.map((r) => {
        const m = r.match(SPEC_REF_RE);
        return m ? specRef(site, page, joinNorm(dir, m[1]!), m[2]!) : code(r);
      }).join(", "),
    ]);
  }
  if (a.assumes.length > 0) facts.push(["Assumes", a.assumes.map(idLink).join(", ")]);
  const supersedes = [...site.adrs.values()]
    .filter((o) => dirOf(o.key) === dir && o.adr.supersededBy === a.id && a.id !== "")
    .map((o) => `[${adrLabel(o)}](${href(relative(dirOf(page), o.page))})`);
  if (supersedes.length > 0) facts.push(["Supersedes", supersedes.join(", ")]);
  const linked = site.linkedFrom.get(key) ?? [];
  if (linked.length > 0) {
    facts.push(["Decides", linked.map((l) => specRef(site, page, l.spec, l.id)).join(", ")]);
  }
  facts.push(["Source", sourceLink(site, page, key)]);
  s += factList(facts);

  if (a.question) s += `## Question\n\n${para(a.question)}\n\n`;
  const bullets = (xs: string[]) => xs.map((x) => `- ${esc(x)}\n`).join("") + "\n";
  if (a.forces.length > 0) s += "## Forces\n\n" + bullets(a.forces);

  if (chosen) {
    s += `## Decision\n\n**${chosen.id}** — ${esc(chosen.summary)}\n\n`;
    if (chosen.reversibility) s += `Reversibility: ${esc(chosen.reversibility)}\n\n`;
  }
  if (a.requires.length > 0) {
    s += "## Obligations\n\nWhat the decision obliges the implementation to do.\n\n";
    s += a.requires.map((r) => `- **${r.id}** — ${esc(r.must)}\n`).join("") + "\n";
  }
  if (a.accepts.length > 0) s += "## Accepted costs\n\n" + bullets(a.accepts);
  if (a.revisit.length > 0) s += "## Revisit when\n\n" + bullets(a.revisit);

  if (a.options.length > 0) {
    s += "## Options considered\n\n";
    s += table(
      ["", "Option", "Reversibility"],
      a.options.map((o) => [
        o.id === a.decision ? `**${o.id}** (chosen)` : o.id,
        esc(o.summary),
        esc(o.reversibility),
      ]),
    ) + "\n";
    const dims = new Map(a.dimensions.map((d) => [d.id, d]));
    for (const o of a.options) {
      s += `### ${o.id} · ${esc(o.summary)}${o.id === a.decision ? " (chosen)" : ""}\n\n`;
      if (o.refs.length > 0) {
        s += `References: ${
          o.refs.map((r) => `${esc(r.label)} ${locator(r.locator)}`).join(" · ")
        }\n\n`;
      }
      for (const c of o.against) {
        const d = dims.get(c.dim);
        s += `- **${c.dim}**${d?.unit ? ` (${esc(d.unit)})` : ""} — ${esc(c.text)}\n`;
      }
      s += "\n";
    }
  }
  if (a.dimensions.length > 0) {
    s += "## Dimensions\n\nWhat every option was judged against.\n\n";
    for (const d of a.dimensions) {
      const extra: string[] = [];
      if (d.unit) extra.push(`unit: ${esc(d.unit)}`);
      if (d.basis.length > 0) extra.push(`basis: ${d.basis.join(", ")}`);
      if (d.source) extra.push(`source: ${esc(d.source)}`);
      s += `- **${d.id}** — ${esc(d.matters)}${
        extra.length > 0 ? ` *(${extra.join("; ")})*` : ""
      }\n`;
    }
    s += "\n";
  }
  if (a.basis.length > 0) {
    s += "## Basis\n\nThe quantities the dimensions are stated under.\n\n";
    s += table(
      ["", "Quantity", "Source"],
      a.basis.map((b) => [b.id, esc(b.quantity), esc(b.source)]),
    ) + "\n";
  }
  return s.replace(/\n+$/, "\n");
}

// ── index page ────────────────────────────────────────────────────────────

function renderIndex(site: Site, title: string): string {
  const specs = [...site.specs.values()];
  const adrs = [...site.adrs.values()];
  const systems = [...new Set(specs.map((s) => s.doc.system))].sort();

  let s = header(`the specs under ${title}`);
  s += `# ${esc(title)}\n\n`;
  s += `${plural(systems.length, "system")} · ${plural(specs.length, "scope")} · ` +
    `${plural(adrs.length, "decision")}\n\n`;

  if (systems.length > 0) s += "## Systems\n\n";
  for (const sys of systems) {
    s += `<a id="${sys}"></a>\n\n### ${esc(sys)}\n\n`;
    s += table(
      ["Scope", "Summary", "Caller", "Blast radius"],
      specs.filter((p) => p.doc.system === sys).map((p) => [
        specRef(site, "index.md", p.doc.key),
        esc(p.doc.summary),
        cap(esc(p.doc.front)),
        cap(esc(p.doc.blastRadius)),
      ]),
    ) + "\n";
  }

  const composites = specs.filter((p) => p.doc.members.length > 0);
  if (composites.length > 0) {
    s +=
      "## Composition\n\nWhich scope is built from which; arrows are labelled with the member alias.\n\n";
    const nodeId = new Map(specs.map((p, i) => [p.doc.key, `s${i}`]));
    const q = (x: string) => `"${x.replace(/"/g, "#quot;")}"`;
    const L = ["```mermaid", "flowchart TD"];
    const used = new Set<string>();
    const edges: string[] = [];
    for (const c of composites) {
      used.add(c.doc.key);
      for (const m of c.doc.members) {
        const key = joinNorm(dirOf(c.doc.key), m.path);
        if (!nodeId.has(key)) continue;
        used.add(key);
        edges.push(`  ${nodeId.get(c.doc.key)} -->|${q(m.alias)}| ${nodeId.get(key)}`);
      }
    }
    for (const p of specs.filter((x) => used.has(x.doc.key))) {
      L.push(`  ${nodeId.get(p.doc.key)}[${q(p.doc.topic || baseOf(p.doc.key))}]`);
    }
    L.push(...edges);
    s += L.join("\n") + "\n```\n\n";
  }

  if (adrs.length > 0) {
    s += "## Decisions\n\nEvery record, including rejected and superseded ones, as history.\n\n";
    s += table(
      ["Record", "Status", "Date"],
      adrs.map((a) => [
        `[${adrLabel(a)}](${href(a.page)})`,
        cap(esc(a.adr.status)),
        esc(a.adr.date),
      ]),
    ) + "\n";
  }
  return s.replace(/\n+$/, "\n");
}

// ── command ───────────────────────────────────────────────────────────────

interface Skipped {
  file: string;
  reason: string;
}

/** Build every page in memory: path inside TARGET → content. */
function buildSite(
  src: string,
  targetAbs: string,
): { pages: Map<string, string>; skipped: Skipped[] } | string {
  const skipped: Skipped[] = [];
  const srcAbs = absPath(src);
  // Keys are paths relative to SRC, so the pages never depend on how SRC was spelled.
  const keyOf = (f: string): string => relative(srcAbs, absPath(f));
  const site: Site = {
    srcAbs,
    targetAbs,
    specs: new Map(),
    adrs: new Map(),
    usedBy: new Map(),
    linkedFrom: new Map(),
  };

  const claimed = new Map<string, string>();
  const claim = (page: string, key: string): string | null => {
    const prior = claimed.get(page);
    if (prior !== undefined) {
      return `two files map to the same page ${page}:\n  ${prior}\n  ${key}\n` +
        "rename one so their basenames differ";
    }
    claimed.set(page, key);
    return null;
  };
  claimed.set("index.md", "(the index)");

  for (const f of listSpecs(src)) {
    let text: string;
    try {
      text = Deno.readTextFileSync(f);
    } catch {
      skipped.push({ file: f, reason: "unreadable" });
      continue;
    }
    const { records, parseErrors } = flatten(text);
    if (parseErrors.length > 0) {
      skipped.push({ file: f, reason: "parse error (run `yamlet verify`)" });
      continue;
    }
    const key = keyOf(f);
    const doc = parseSpec(key, records);
    if (doc.system === "") {
      skipped.push({ file: f, reason: "no system" });
      continue;
    }
    const page = `${doc.system}/${baseOf(key).replace(/\.yamlet\.yaml$/, "")}.md`;
    const clash = claim(page, f);
    if (clash) return clash;
    site.specs.set(key, { page, doc });
  }

  for (const f of listFiles(src, ".adr.yaml")) {
    const loaded = loadAdr(f);
    if (!loaded) {
      skipped.push({ file: f, reason: "parse error (run `yamlet verify`)" });
      continue;
    }
    const key = keyOf(f);
    const page = `decisions/${key.replace(/\.adr\.yaml$/, "")}.md`;
    const clash = claim(page, f);
    if (clash) return clash;
    site.adrs.set(key, { key, page, adr: loaded.adr });
  }

  // Inverse indexes: the format holds none on purpose; a derived page may.
  for (const { doc } of site.specs.values()) {
    const dir = dirOf(doc.key);
    for (const m of doc.members) {
      const k = joinNorm(dir, m.path);
      site.usedBy.set(k, [...(site.usedBy.get(k) ?? []), { composite: doc.key, alias: m.alias }]);
    }
    const link = (adrs: string[], id: string) => {
      for (const a of adrs) {
        const k = joinNorm(dir, a);
        site.linkedFrom.set(k, [...(site.linkedFrom.get(k) ?? []), { spec: doc.key, id }]);
      }
    };
    for (const rq of doc.requirements) {
      link(rq.adrs, rq.id);
      for (const ac of rq.criteria) link(ac.adrs, ac.id);
    }
  }

  const pages = new Map<string, string>();
  const title = baseOf(srcAbs) || src;
  pages.set("index.md", renderIndex(site, title));
  for (const sp of site.specs.values()) pages.set(sp.page, renderSpec(site, sp));
  for (const ap of site.adrs.values()) pages.set(ap.page, renderAdr(site, ap));
  return { pages, skipped };
}

/** Every file under `dir`, as paths relative to it (dotfiles included — they are ours too). */
function treeOf(dir: string, rel = "", acc: string[] = []): string[] {
  let entries: Deno.DirEntry[];
  try {
    entries = [...Deno.readDirSync(rel === "" ? dir : `${dir}/${rel}`)];
  } catch {
    return acc;
  }
  for (const e of entries) {
    const p = rel === "" ? e.name : `${rel}/${e.name}`;
    if (e.isDirectory) treeOf(dir, p, acc);
    else acc.push(p);
  }
  return acc.sort();
}

function readOr(p: string): string | null {
  try {
    return Deno.readTextFileSync(p);
  } catch {
    return null;
  }
}

export function runDocs(args: string[]): CmdResult {
  let check = false;
  const positionals: string[] = [];
  for (const a of args) {
    if (a === "--check") check = true;
    else if (a.startsWith("-")) return die(`unknown flag for docs: ${a}`);
    else positionals.push(a);
  }
  if (positionals.length < 2) {
    return die("docs requires a source directory and a target directory: yamlet docs SRC TARGET");
  }
  if (positionals.length > 2) return die(`too many arguments: ${positionals[2]}`);
  const src = positionals[0]!;
  const target = positionals[1]!;

  try {
    if (!Deno.statSync(src).isDirectory) return die(`not a directory: ${src}`);
  } catch {
    return die(`source directory not found: ${src}`);
  }
  let targetExists = false;
  try {
    if (!Deno.statSync(target).isDirectory) {
      return die(`target exists but is not a directory: ${target}`);
    }
    targetExists = true;
  } catch {
    // Created below.
  }
  const srcAbs = absPath(src);
  const targetAbs = absPath(target);
  if (srcAbs === targetAbs || srcAbs.startsWith(targetAbs + "/")) {
    return die(`TARGET ${target} contains SRC ${src}: a run would erase the specs`);
  }

  const built = buildSite(src, targetAbs);
  if (typeof built === "string") return die(built);
  const { pages, skipped } = built;
  const skippedText = skipped.length === 0 ? "" : `skipped ${plural(skipped.length, "file")}:\n` +
    skipped.map((s) => `  ${s.file} — ${s.reason}\n`).join("");

  if (check) {
    const drift: string[] = [];
    const existing = new Set(targetExists ? treeOf(target) : []);
    for (const [p, content] of [...pages].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))) {
      const have = existing.has(p) ? readOr(`${target}/${p}`) : null;
      if (have === null) drift.push(`  missing  ${target}/${p}`);
      else if (have !== content) drift.push(`  changed  ${target}/${p}`);
    }
    for (const p of existing) if (!pages.has(p)) drift.push(`  extra    ${target}/${p}`);
    if (drift.length === 0) {
      return {
        exitCode: 0,
        stdout: `${target} is up to date (${plural(pages.size, "page")})\n` + skippedText,
        stderr: "",
      };
    }
    return {
      exitCode: 1,
      stdout: skippedText,
      stderr: `${target} is out of date with ${src}:\n${drift.join("\n")}\n` +
        `regenerate with: yamlet docs ${src} ${target}\n`,
    };
  }

  // TARGET is ours — but only once it has proved it: never wipe a directory of someone's own docs.
  if (targetExists && treeOf(target).length > 0) {
    const index = readOr(`${target}/index.md`);
    if (index === null || !index.startsWith(MARKER)) {
      return die(
        `${target} is not empty and was not written by \`yamlet docs\` (no generated index.md); ` +
          "refusing to erase it — pick an empty or new directory",
      );
    }
  }
  try {
    for (const e of targetExists ? [...Deno.readDirSync(target)] : []) {
      Deno.removeSync(`${target}/${e.name}`, { recursive: true });
    }
    for (const [p, content] of pages) {
      const dir = dirOf(p);
      Deno.mkdirSync(dir === "" ? target : `${target}/${dir}`, { recursive: true });
      Deno.writeTextFileSync(`${target}/${p}`, content);
    }
  } catch (e) {
    return die(`could not write ${target}: ${e instanceof Error ? e.message : String(e)}`);
  }

  const specs = [...pages.keys()].filter((p) => p !== "index.md" && !p.startsWith("decisions/"));
  const adrs = pages.size - 1 - specs.length;
  const stdout = `wrote ${plural(pages.size, "page")} to ${target} ` +
    `(${plural(specs.length, "scope")}, ${plural(adrs, "decision")}, index.md)\n` + skippedText;
  return { exitCode: 0, stdout, stderr: "" };
}

export const docsCommand: Command = {
  name: "docs",
  summary: "render specs and decision records as Markdown pages for people",
  help: `yamlet docs — render specs and decision records as Markdown pages

Usage:
  yamlet docs SRC TARGET [--check]

Arguments:
  SRC      directory to scan for *.yamlet.yaml specs and *.adr.yaml decision records
  TARGET   directory to write the pages into (created if absent)

Options:
  --check  write nothing; compare TARGET with what a run would write and exit 1
           if any page is missing, changed or no longer produced. Use it in CI so
           committed pages cannot drift from their sources.

Writes, for readers who never run yamlet (teammates, stakeholders, a browser on
the code host):
  TARGET/index.md                every system and its scopes, every decision, and
                                 a diagram of which composite holds which scope
  TARGET/<system>/<scope>.md     one per spec: contract, members and wiring, each
                                 acceptance criterion as an EARS sentence, the
                                 decisions that decide it, the composites using it
  TARGET/decisions/<path>.md     one per decision record, whatever its status —
                                 rejected and superseded records are history and
                                 are marked as such

Tech specs are not rendered: they are disposable plans (see \`yamlet trace\`).

The pages are a view; the YAML stays the source. Every page says so in its
first line and links its source file. TARGET is a yamlet-owned directory: every
run wipes it and rebuilds, so a renamed or deleted spec leaves no orphan page. A
non-empty TARGET without a generated index.md is refused rather than erased, and
so is a TARGET that contains SRC.

It parses, it does not validate: an unparseable file is skipped and listed, and
a link that resolves to nothing renders as plain text. Run \`yamlet verify\` first.

Exit: 0 ok or up to date · 1 --check found drift · 2 usage/path/collision/write error
`,
  run: runDocs,
};
